### ISSUE TITLE
你的项目是什么作用呢？谢谢回答

### ISSUE THREAD

**Issue by zzlTim** [812781385/ollama-webUI#1]
仅仅改变ollamawebui显示吗？

**Comment by 812781385** [comment]
> 仅仅改变ollamawebui显示吗？

项目分为两个部分：client、serve。

当你安装完成ollama后，就可以实现本地可视化聊天。
1. client不仅可以实现聊天任务，还可以控制管理你的ollama，UI界面开源可以自由修改，并且支持移动端适配。
2. serve实现api接口，包含RAG底层逻辑。
