### ISSUE TITLE
出现跨域请求失败的情况了，我该怎么办？

### ISSUE THREAD

**Issue by bluesiboy** [812781385/ollama-webUI#2]
```
pacman -S /ollama-rocm
ollama serve
```

![image](https://github.com/user-attachments/assets/d48c6038-e8c0-4475-8d0f-48591706eb1e)

![image](https://github.com/user-attachments/assets/528f40c9-f5ae-4f77-a716-80ee3c0f37ab)

**Comment by 812781385** [comment]
你应该还需要启动serve，有两个选择:nodejs或python来运行。
如果选择nodejs:
则VITE_APP_AXIOS_BASE_URL=http://你的ip:7001
如果选择python:
则VITE_APP_AXIOS_BASE_URL=http://你的ip:7010





---原始邮件---
发件人: "Blue ***@***.***&gt;
发送时间: 2024年8月1日(周四) 晚上8:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [812781385/ollama-webUI] 出现跨域请求失败的情况了，我该怎么办？ (Issue #2)




 pacman -S /ollama-rocm ollama serve  
image.png (view on web)
 
image.png (view on web)

**Comment by 812781385** [comment]
目前服务端端口统一为7001
